services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ori6in
      POSTGRES_PASSWORD: ori6in
      POSTGRES_DB: ori6in
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  mongo_data:
